In [1]:
pip install numpy

Collecting numpy
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 3.9 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.6 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 2.3 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.6 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 3.0 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.6 MB 3.0 MB/s eta 0:00:03
   ----------------------- ---------------- 7.3/12.6 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 2.9 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 2.9 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.6 MB 2.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.6 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 2.6 MB/s  0:00:04
Installing collected packages: numpy
Successfully installed numpy-2.5.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\khush\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [2]:
import numpy as np

In [2]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]

In [3]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [4]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [5]:
print(np.random.randint(1,100, size=(4,4)))

[[22 70 60 90]
 [88 62  8 38]
 [68  9 61 91]
 [30 63 93 48]]

In [7]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]

In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]

In [3]:
arr=np.array([10,20,30,40])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

100
25.0
11.180339887498949
125.0
10
40

In [4]:
print(np.random.choice([10,20,30], size=4))

[10 20 20 20]

In [5]:
#shuffle
arr=np.arange(50)
np.random.shuffle(arr)
print(arr)

[26 39 12 16  4 21 38 42 15 47 29 45 49 20 19  9 22 32 37 11 18  8 24 10
  1 31 48  7 27  3 13 35 43 14 46  2 23 17 36 28 44 33  5 40 34  6  0 25
 30 41]

In [6]:
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr > 5])

[6 7 8 9]

In [9]:
#where
arr=np.array([10,20,30,40])
print(np.where(arr > 30))

(array([3]),)

In [ ]:
#sorting

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\khush\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\khush\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\khush\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/10.0 MB 202.5 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.0/10.0 MB 189.8 kB/s eta 0:00:47
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ----- ---------------------------------- 1.3/10.0 MB 173.5 kB/s eta 0:00:50
   ------ --------------------------------- 1.6/10.0 MB 170.4 kB/s eta 0:00:50
   ------ --------------------------------- 1.6/10.0 MB 170.4 kB/s eta 0:00:50
   ------ --------------------------------- 1.6/10.0 MB 170.4 kB/s eta 0:00:50
   ------ --------------------------------- 1.6/10.0 MB 170.4 kB/s eta 0:00:50
   ------- -------------------------------- 1.8/10.0 MB 178.7 kB/s eta 0:00:46
   ------- -------------------------------- 1.8/10.0 MB 178.7 kB/s eta 0:00:46
   ------- -------------------------------- 1.8/10.0 MB 178.7 kB/s eta 0:00:46
   ------- -------------------------------- 1.8/10.0 MB 178.7 kB/s eta 0:00:46
   -------- ------------------------------- 2.1/10.0 MB 189.7 kB/s eta 0:00:42
   -------- ------------------------------- 2.1/10.0 MB 189.7 kB/s eta 0:00:42
   --------- ------------------------------ 2.4/10.0 MB 200.1 kB/s eta 0:00:38
   --------- ------------------------------ 2.4/10.0 MB 200.1 kB/s eta 0:00:38
   --------- ------------------------------ 2.4/10.0 MB 200.1 kB/s eta 0:00:38
   --------- ------------------------------ 2.4/10.0 MB 200.1 kB/s eta 0:00:38
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ---------- ----------------------------- 2.6/10.0 MB 207.0 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ----------- ---------------------------- 2.9/10.0 MB 205.7 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------ --------------------------- 3.1/10.0 MB 195.9 kB/s eta 0:00:35
   ------------- -------------------------- 3.4/10.0 MB 189.5 kB/s eta 0:00:35
   ------------- -------------------------- 3.4/10.0 MB 189.5 kB/s eta 0:00:35
   ------------- -------------------------- 3.4/10.0 MB 189.5 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/10.0 MB 197.6 kB/s eta 0:00:32
   -------------- ------------------------- 3.7/10.0 MB 197.6 kB/s eta 0:00:32
   -------------- ------------------------- 3.7/10.0 MB 197.6 kB/s eta 0:00:32
   -------------- ------------------------- 3.7/10.0 MB 197.6 kB/s eta 0:00:32
   -------------- ------------------------- 3.7/10.0 MB 197.6 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   --------------- ------------------------ 3.9/10.0 MB 200.1 kB/s eta 0:00:31
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ---------------- ----------------------- 4.2/10.0 MB 194.0 kB/s eta 0:00:30
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ----------------- ---------------------- 4.5/10.0 MB 193.6 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   ------------------ --------------------- 4.7/10.0 MB 181.9 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/10.0 MB 181.4 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/10.0 MB 180.7 kB/s eta 0:00:27
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/10.0 MB 176.0 kB/s eta 0:00:26
   ----------------------- ---------------- 5.8/10.0 MB 174.8 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/10.0 MB 174.8 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/10.0 MB 174.8 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/10.0 MB 174.8 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/10.0 MB 174.8 kB/s eta 0:00:24
   ------------------------ --------------- 6.0/10.0 MB 174.3 kB/s eta 0:00:23
   ------------------------ --------------- 6.0/10.0 MB 174.3 kB/s eta 0:00:23
   ------------------------ --------------- 6.0/10.0 MB 174.3 kB/s eta 0:00:23
   ------------------------ --------------- 6.0/10.0 MB 174.3 kB/s eta 0:00:23
   ------------------------ --------------- 6.0/10.0 MB 174.3 kB/s eta 0:00:23
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/10.0 MB 176.1 kB/s eta 0:00:21
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/10.0 MB 175.2 kB/s eta 0:00:20
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/10.0 MB 168.8 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ---------------------------- ----------- 7.1/10.0 MB 158.0 kB/s eta 0:00:19
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ----------------------------- ---------- 7.3/10.0 MB 147.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------ --------- 7.6/10.0 MB 133.3 kB/s eta 0:00:18
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   ------------------------------- -------- 7.9/10.0 MB 129.0 kB/s eta 0:00:17
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   -------------------------------- ------- 8.1/10.0 MB 127.2 kB/s eta 0:00:15
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   --------------------------------- ------ 8.4/10.0 MB 126.4 kB/s eta 0:00:13
   ---------------------------------- ----- 8.7/10.0 MB 119.6 kB/s eta 0:00:11
   ---------------------------------- ----- 8.7/10.0 MB 119.6 kB/s eta 0:00:11
   ---------------------------------- ----- 8.7/10.0 MB 119.6 kB/s eta 0:00:11
   ---------------------------------- ----- 8.7/10.0 MB 119.6 kB/s eta 0:00:11
   ---------------------------------- ----- 8.7/10.0 MB 119.6 kB/s eta 0:00:11
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09
   ----------------------------------- ---- 8.9/10.0 MB 118.7 kB/s eta 0:00:09

In [2]:
import pandas as pd

In [3]:
import pandas as pd
marks = pd.Series([90, 80, 70, 60, 50])
print(marks)

0    90
1    80
2    70
3    60
4    50
dtype: int64

In [5]:
import pandas as pd
data={
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "marks": [90, 80, 70, 60]
}
df=pd.DataFrame(data)

In [6]:
df

      Name  Age  marks
0    Alice   25     90
1      Bob   30     80
2  Charlie   35     70
3    David   40     60

In [8]:
pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.9-cp314-cp314-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.9-cp314-cp314-win_amd64.whl (162 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.7.22 charset_normalizer-3.4.9 idna-3.18 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script idna.exe is installed in 'c:\Users\khush\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'c:\Users\khush\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [10]:
import requests
from io import StringIO

In [11]:
pd.read_csv(StringIO(requests.get("https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv").text))

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

In [13]:
url="https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
headers ={"UnicodeTranslateError": "ignore"}

In [2]:
import numpy as np
import pandas as pd

In [ ]:
data =pd.read_csv